overrides:
  form-data: 4.0.6
  js-yaml: ^4.3.2
  postcss: ^8.5.28
  '@electron/get>undici': ^7.29.1

allowBuilds:
  electron: true
  electron-winstaller: true
  javascript-obfuscator: true
  sharp: true
  ffmpeg-static: true
  esbuild: false
  vue-demi: false
  '@parcel/watcher': false
