allowBuilds:
  electron: true
  electron-winstaller: true
  javascript-obfuscator: true
  sharp: true
  asarmor: true
  ffmpeg-static: true
  esbuild: false
  vue-demi: false
  '@parcel/watcher': false
